### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by justcop** [north3221/home-assistant-config#1]
This looks brilliant and exactly what I've been looking for.

Any hints on how to install this. As a relatively new home assistant user I'm not so familar with useage of automations outside the UI.

I pasted this into a yaml for a new automation and that didn't seem to work.

Installation instructions for other noobs, on the readme would be much appreciated!!

**Comment by north3221** [comment]
Come on, I share the config to help others, I cant take you from zero to using a complex automation.

You need to familiarise yourself with using yaml automations, take a look at the docs: [Automation triggers](https://www.home-assistant.io/docs/automation/trigger/)

In fact use the simple example I put on the Tado page when I did the PR for this: [Tado integration](https://www.home-assistant.io/integrations/tado/)

build yourself a simple automation so you understand the principle and then try mine. It is as simple as copy and paste but you need to understand what you are doing and read the notes I put in the yaml as that explains each part and what you need to do.
