### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by randy993** [north3221/home-assistant-config#2]
Hiya,

Recently tried to use your script, looks great. However, I get an unhandled exception error in my logging when it is triggered. Do you have any idea what could be the problem?

`2021-03-02 10:21:04 ERROR (MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1152, in _sendfile_fallback
read = await self.run_in_executor(None, file.readinto, view)
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 485, in start
resp, reset = await task
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 440, in _handle_request
reset = await self.finish_response(request, resp, start_time)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 591, in finish_response
await prepare_meth(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_fileresponse.py", line 241, in prepare
return await self._sendfile(request, fobj, offset, count)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_fileresponse.py", line 96, in _sendfile
await loop.sendfile(transport, fobj, offset, count)
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1131, in sendfile
return await self._sendfile_fallback(transport, file,
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1161, in _sendfile_fallback
await proto.restore()
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 263, in restore
self._transport.resume_reading()
File "/usr/local/lib/python3.8/asyncio/sslproto.py", line 344, in resume_reading
self._ssl_protocol._transport.resume_reading()
AttributeError: 'NoneType' object has no attribute 'resume_reading'`

My config, see attachment due to format issues on Github
[tado_offset.yaml](https://github.com/north3221/home-assistant-config/files/6067568/tado_offset.yaml)

.

**Comment by north3221** [comment]
That's a bit odd, are you sure its when this automation triggers? That's a ssl error on aiohttp. The Tado integration does use that, what version of HA are you running?

**Comment by randy993** [comment]
Thanks for your fast response. I'm fairly sure this error resulted from implementing this automation. I reverted back to my old configuration using a simpler version of the offset correction from this topic (https://community.home-assistant.io/t/tado-integration-put-offset/175964/40), and the error does not occur anymore.

I created a snapshot of the configuration with your automation as well, so if you want me to do more testing I can do that. Might need a little assistance/guiding in what/how to test though.

**Comment by north3221** [comment]
What version of HA?

Also go to dev tools and get the state of your tado climate devices and see if they all have the following attributes:

```yml
offset_last_updated:
offset_last_changed:
```

**Comment by randy993** [comment]
Ah, excuse me. Missed that question. Currently running version core-2021.2.3. 

hvac_modes: off, auto, heat
min_temp: 5
max_temp: 25
target_temp_step: 1
preset_modes: away, home
current_temperature: 15.8
temperature: 15.8
current_humidity: 58.1
hvac_action: off
preset_mode: home
offset_celsius: 0
offset_fahrenheit: 0
friendly_name: badkamer_tado
supported_features: 17

No offset_last_updated/changed.

**Comment by north3221** [comment]
Ignore me I haven't put that PR in yet! I think maybe someone has changed something in Tado integration. Just had a quick look at PRs and cant see anything obvious, but not sure. I cant easily roll back to the official Tado integration because I changed some options. I need to spend a bit of time looking at it and getting the PR in.

In the meantime there are a couple of things you could do

1 increase your logging for the Tado component to debug, maybe for aiohttp too lets see what else is in there

2 install my version of the Tado integration as a custom_component. NB if you do this and want to roll back you would need to uninstall/reinstall it due to me changing some options that dont yet exists on the official one. but you could just leave my custom one in till my PR is in then going back to official will be easy

**Comment by randy993** [comment]
Hmm, could it be due to the missing offset parameters?

I increased the logging from the Tado component and reproduced the error. I don't see anything odd in there.

[tado logging.txt](https://github.com/north3221/home-assistant-config/files/6068747/tado.logging.txt)

**Comment by north3221** [comment]
Ahh its a water heater. You wouldn't have an offset for a water heater.  Do you have a water heater and thermostat in that zone (zone 0)?

**Comment by randy993** [comment]
Yes, that's right. I have boiler for both heating water and heating radiators. In my Tado configuration, it is seen as a separate room. 
![image](https://user-images.githubusercontent.com/47896624/109654271-4d5ec500-7b62-11eb-99a5-b626337dda2c.png)

In homeassistant, there is an entity called: water_heater.hot_water.
As you can see, I did not integrate it in your config though.

Could this be the issue? That it's trying to set an offset for the hot water entity?

**Comment by north3221** [comment]
Yeah its the 'zone' that gets the offset update, so I think there is something that's causing the issue. for now split them into separate zones and make sure that reflects in HA, so basically the hot water is ion a one on its own that you are not triggering in my automation script.

Lets see if that works and then we can look for a proper fix later

**Comment by randy993** [comment]
I'm not really sure what you mean. The hot water already appears to be a separate zone (zone 0). 

![image](https://user-images.githubusercontent.com/47896624/109655412-89def080-7b63-11eb-9021-239a1c5ab243.png)

When looking in the debug logging, this call gets done more often and does not return any errors.

**Comment by randy993** [comment]
Hmm. I reverted back to my original set-up and noticed that I get the same error. I'm wondering whether the issue of not updating the offset is related to this error now.

**Comment by north3221** [comment]
Yeah zone 0 is your water heater and the one that errors. There is some issue with the connection to Tado there though, its not receiving all the data. Take a look [](https://github.com/encode/httpx/issues/1213.) Not tado but same issue

Tado are looking to rate limit, so it may be to do with that. With my code I have the backoff set, but without my code that bit does nothing for you, so you maybe hitting the rate limit. The integration itself refreshes every 15 secs, that's what is erroring for you not my offset update. However, with my automation you might be updating offsets more regularly so finding this issue more often (as hitting Tado API more)
