### ISSUE TITLE
offset last changed is not an available attribute

### ISSUE THREAD

**Issue by justcop** [north3221/home-assistant-config#3]
unless I'm missing something, it doesn't look like this state attribute that you've referenced has any value.
This means that the limiting the timing condition doesn't work as far as I can see
state_attr(climate_id, 'offset_last_changed')

**Comment by north3221** [comment]
Yeah did you read the NB in the README? Needs a PR, just haven't got round to it yet. Works for me, does nothing for anyone else... yet

**Comment by justcop** [comment]
#4 
I have posted a patch which I believe fixes this.
Forgive any mistakes, I am a very amateur coder.
